### ISSUE TITLE
Create a communication standard (using bits)

### ISSUE THREAD

**Issue by nikolaevra** [teamwaterloop/waterloop-website#9]
Define a structure to send messages from embedded to backend

┆Attachments: <a href="https:&#x2F;&#x2F;github.com&#x2F;teamwaterloop&#x2F;wlib&#x2F;issues&#x2F;3">#3 communication packets standard</a>

**Comment by dhillondeep** [comment]
This is more suitable for embedded to come up with this that you guys can implement on your side
